
[root@centos7 aaron]# kubectl get certificate httpbin-cert -n istio-system
NAME           READY   SECRET     AGE
httpbin-cert   False   xip-cert   3d4h

[root@centos7 aaron]# kubectl describe certificate httpbin-cert -n istio-system
Name:         httpbin-cert
Namespace:    istio-system
Labels:       <none>
Annotations:  <none>
API Version:  cert-manager.io/v1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2022-04-02T13:27:06Z
  Generation:          1
  Managed Fields:
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:commonName:
        f:dnsNames:
        f:issuerRef:
          .:
          f:kind:
          f:name:
        f:secretName:
    Manager:      kubectl-create
    Operation:    Update
    Time:         2022-04-02T13:27:06Z
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:lastFailureTime:
    Manager:         controller
    Operation:       Update
    Subresource:     status
    Time:            2022-04-05T17:34:34Z
  Resource Version:  1641321
  Self Link:         /apis/cert-manager.io/v1/namespaces/istio-system/certificates/httpbin-cert
  UID:               d181e445-f7d7-413f-97c8-fc0e1f01a1ed
Spec:
  Common Name:  httpbin.192.168.32.100.xip.io
  Dns Names:
    httpbin.192.168.32.100.xip.io
  Issuer Ref:
    Kind:       ClusterIssuer
    Name:       letsencrypt-staging
  Secret Name:  xip-cert
Status:
  Conditions:
    Last Transition Time:  2022-04-02T13:27:06Z
    Message:               Issuing certificate as Secret does not exist
    Observed Generation:   1
    Reason:                DoesNotExist
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-04-05T17:35:00Z
    Message:               The certificate request has failed to complete and will be retried: Failed to wait for order resource "httpbin-cert-shfrw-305099323" to become ready: order is in "invalid" state: 
    Observed Generation:   1
    Reason:                Failed
    Status:                False
    Type:                  Issuing
  Last Failure Time:       2022-04-05T17:35:00Z
Events:
  Type     Reason     Age                From          Message
  ----     ------     ----               ----          -------
  Normal   Issuing    27m (x2 over 88m)  cert-manager  Issuing certificate as Secret does not exist
  Normal   Generated  27m                cert-manager  Stored new private key in temporary Secret resource "httpbin-cert-pttxn"
  Normal   Requested  27m                cert-manager  Created new CertificateRequest resource "httpbin-cert-shfrw"
  Warning  Failed     26m                cert-manager  The certificate request has failed to complete and will be retried: Failed to wait for order resource "httpbin-cert-shfrw-305099323" to become ready: order is in "invalid" state:



[root@centos7 aaron]# kubectl get pod -n cert-manager
NAME                                       READY   STATUS    RESTARTS      AGE
cert-manager-79d88dc59b-rnhvp              1/1     Running   2 (98m ago)   3d5h
cert-manager-cainjector-85656d565c-4zh6t   1/1     Running   5 (98m ago)   3d5h
cert-manager-webhook-8665f985d6-7xmdp      1/1     Running   5 (98m ago)   3d5h


[root@centos7 aaron]# kubectl logs cert-manager-79d88dc59b-rnhvp -n cert-manager 
I0405 16:33:23.440712       1 start.go:75] cert-manager "msg"="starting controller"  "git-commit"="2e0bfc87d0c63c473c31a17f4c8c65e89806dc16" "version"="v1.7.2"
W0405 16:33:23.440843       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0405 16:33:23.441544       1 controller.go:302] cert-manager/controller/build-context "msg"="configured acme dns01 nameservers" "nameservers"=["10.96.0.10:53"] 
I0405 16:33:23.442069       1 controller.go:85] cert-manager/controller "msg"="enabled controllers: [certificaterequests-approver certificaterequests-issuer-acme certificaterequests-issuer-ca certificaterequests-issuer-selfsigned certificaterequests-issuer-vault certificaterequests-issuer-venafi certificates-issuing certificates-key-manager certificates-metrics certificates-readiness certificates-request-manager certificates-revision-manager certificates-trigger challenges clusterissuers ingress-shim issuers orders]"  
I0405 16:33:23.442381       1 controller.go:149] cert-manager/controller "msg"="starting leader election"  
I0405 16:33:23.442744       1 leaderelection.go:248] attempting to acquire leader lease kube-system/cert-manager-controller...
I0405 16:33:23.442780       1 controller.go:106] cert-manager/controller "msg"="starting metrics server"  "address"={"IP":"::","Port":9402,"Zone":""}
I0405 16:33:23.486458       1 leaderelection.go:258] successfully acquired lease kube-system/cert-manager-controller
I0405 16:33:23.595958       1 controller.go:197] cert-manager/controller "msg"="not starting controller as it's disabled" "controller"="gateway-shim" 
I0405 16:33:23.596205       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="challenges" 
I0405 16:33:23.596364       1 controller.go:197] cert-manager/controller "msg"="not starting controller as it's disabled" "controller"="certificatesigningrequests-issuer-selfsigned" 
I0405 16:33:23.596400       1 controller.go:197] cert-manager/controller "msg"="not starting controller as it's disabled" "controller"="certificatesigningrequests-issuer-venafi" 
I0405 16:33:23.597805       1 controller.go:197] cert-manager/controller "msg"="not starting controller as it's disabled" "controller"="certificatesigningrequests-issuer-ca" 
I0405 16:33:23.600218       1 controller.go:197] cert-manager/controller "msg"="not starting controller as it's disabled" "controller"="certificatesigningrequests-issuer-acme" 
I0405 16:33:23.600267       1 controller.go:197] cert-manager/controller "msg"="not starting controller as it's disabled" "controller"="certificatesigningrequests-issuer-vault" 
I0405 16:33:23.597974       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificaterequests-issuer-acme" 
I0405 16:33:23.598674       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificates-trigger" 
I0405 16:33:23.599153       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificaterequests-issuer-venafi" 
I0405 16:33:23.599183       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificates-revision-manager" 
I0405 16:33:23.599199       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="issuers" 
I0405 16:33:23.599226       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificates-readiness" 
I0405 16:33:23.599246       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="clusterissuers" 
I0405 16:33:23.599283       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="orders" 
I0405 16:33:23.599301       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="ingress-shim" 
I0405 16:33:23.599316       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificates-issuing" 
I0405 16:33:23.599329       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificaterequests-issuer-ca" 
I0405 16:33:23.599360       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificates-key-manager" 
I0405 16:33:23.600637       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificates-request-manager" 
I0405 16:33:23.616862       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificaterequests-approver" 
I0405 16:33:23.617454       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificaterequests-issuer-selfsigned" 
I0405 16:33:23.617695       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificaterequests-issuer-vault" 
I0405 16:33:23.617967       1 controller.go:220] cert-manager/controller "msg"="starting controller" "controller"="certificates-metrics" 
I0405 16:33:23.620681       1 util.go:84] cert-manager/controller/certificaterequests/handleOwnedResource "msg"="owning resource not found in cache" "related_resource_kind"="CertificateRequest" "related_resource_name"="httpbin-cert-vw2kl" "related_resource_namespace"="istio-system" "resource_kind"="Order" "resource_name"="httpbin-cert-vw2kl-305099323" "resource_namespace"="istio-system" "resource_version"="v1" 
I0405 16:33:23.802009       1 trigger_controller.go:181] cert-manager/certificates-trigger "msg"="Certificate must be re-issued" "key"="istio-system/httpbin-cert" "message"="Issuing certificate as Secret does not exist" "reason"="DoesNotExist"
I0405 16:33:23.802086       1 conditions.go:190] Found status change for Certificate "httpbin-cert" condition "Issuing": "False" -> "True"; setting lastTransitionTime to 2022-04-05 16:33:23.802060004 +0000 UTC m=+0.738628083
I0405 16:33:23.802437       1 setup.go:202] cert-manager/clusterissuers "msg"="skipping re-verifying ACME account as cached registration details look sufficient" "related_resource_kind"="Secret" "related_resource_name"="letsencrypt-prod" "related_resource_namespace"="cert-manager" "resource_kind"="ClusterIssuer" "resource_name"="letsencrypt-prod" "resource_namespace"="" "resource_version"="v1" 
I0405 16:33:23.802638       1 setup.go:202] cert-manager/clusterissuers "msg"="skipping re-verifying ACME account as cached registration details look sufficient" "related_resource_kind"="Secret" "related_resource_name"="letsencrypt-staging" "related_resource_namespace"="cert-manager" "resource_kind"="ClusterIssuer" "resource_name"="letsencrypt-staging" "resource_namespace"="" "resource_version"="v1" 
I0405 16:33:28.702204       1 setup.go:202] cert-manager/clusterissuers "msg"="skipping re-verifying ACME account as cached registration details look sufficient" "related_resource_kind"="Secret" "related_resource_name"="letsencrypt-staging" "related_resource_namespace"="cert-manager" "resource_kind"="ClusterIssuer" "resource_name"="letsencrypt-staging" "resource_namespace"="" "resource_version"="v1" 
I0405 16:33:28.703827       1 setup.go:202] cert-manager/clusterissuers "msg"="skipping re-verifying ACME account as cached registration details look sufficient" "related_resource_kind"="Secret" "related_resource_name"="letsencrypt-prod" "related_resource_namespace"="cert-manager" "resource_kind"="ClusterIssuer" "resource_name"="letsencrypt-prod" "resource_namespace"="" "resource_version"="v1" 
E0405 16:33:33.813334       1 controller.go:163] cert-manager/certificates-trigger "msg"="re-queuing item due to error processing" "error"="Internal error occurred: failed calling webhook \"webhook.cert-manager.io\": failed to call webhook: Post \"https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s\": context deadline exceeded" "key"="istio-system/httpbin-cert" 
I0405 16:33:34.815010       1 trigger_controller.go:181] cert-manager/certificates-trigger "msg"="Certificate must be re-issued" "key"="istio-system/httpbin-cert" "message"="Issuing certificate as Secret does not exist" "reason"="DoesNotExist"
I0405 16:33:34.815078       1 conditions.go:190] Found status change for Certificate "httpbin-cert" condition "Issuing": "False" -> "True"; setting lastTransitionTime to 2022-04-05 16:33:34.81507185 +0000 UTC m=+11.751639885
I0405 16:33:35.296091       1 issuing_controller.go:265] cert-manager/certificates-issuing "msg"="Found a failed CertificateRequest from previous issuance, waiting for it to be deleted..." "key"="istio-system/httpbin-cert" "resource_kind"="CertificateRequest" "resource_name"="httpbin-cert-vw2kl" "resource_namespace"="istio-system" "resource_version"="v1" 
I0405 16:33:35.329115       1 conditions.go:261] Setting lastTransitionTime for CertificateRequest "httpbin-cert-g9tcp" condition "Approved" to 2022-04-05 16:33:35.329086593 +0000 UTC m=+12.265654646
I0405 16:33:35.356756       1 util.go:84] cert-manager/controller/certificaterequests/handleOwnedResource "msg"="owning resource not found in cache" "related_resource_kind"="CertificateRequest" "related_resource_name"="httpbin-cert-vw2kl" "related_resource_namespace"="istio-system" "resource_kind"="Order" "resource_name"="httpbin-cert-vw2kl-305099323" "resource_namespace"="istio-system" "resource_version"="v1" 
E0405 16:33:35.356778       1 controller.go:171] cert-manager/orders "msg"="order in work queue no longer exists" "error"="order.acme.cert-manager.io \"httpbin-cert-vw2kl-305099323\" not found"  
I0405 16:33:35.367925       1 util.go:84] cert-manager/controller/orders/handleOwnedResource "msg"="owning resource not found in cache" "related_resource_kind"="Order" "related_resource_name"="httpbin-cert-vw2kl-305099323" "related_resource_namespace"="istio-system" "resource_kind"="Challenge" "resource_name"="httpbin-cert-vw2kl-305099323-2162626058" "resource_namespace"="istio-system" "resource_version"="v1" 
I0405 16:33:35.368479       1 conditions.go:261] Setting lastTransitionTime for CertificateRequest "httpbin-cert-g9tcp" condition "Ready" to 2022-04-05 16:33:35.368473207 +0000 UTC m=+12.305041220
I0405 16:33:35.429524       1 util.go:84] cert-manager/controller/orders/handleOwnedResource "msg"="owning resource not found in cache" "related_resource_kind"="Order" "related_resource_name"="httpbin-cert-vw2kl-305099323" "related_resource_namespace"="istio-system" "resource_kind"="Challenge" "resource_name"="httpbin-cert-vw2kl-305099323-2162626058" "resource_namespace"="istio-system" "resource_version"="v1" 
E0405 16:33:35.430411       1 controller.go:211] cert-manager/challenges "msg"="challenge in work queue no longer exists" "error"="challenge.acme.cert-manager.io \"httpbin-cert-vw2kl-305099323-2162626058\" not found"  
I0405 16:33:41.973303       1 pod.go:71] cert-manager/challenges/http01/ensurePod "msg"="creating HTTP01 challenge solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:33:42.044050       1 pod.go:59] cert-manager/challenges/http01/selfCheck/http01/ensurePod "msg"="found one existing HTTP01 solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-phmlg" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:33:42.044191       1 service.go:43] cert-manager/challenges/http01/selfCheck/http01/ensureService "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-jcbkd" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 16:33:42.057481       1 sync.go:186] cert-manager/challenges "msg"="propagation check failed" "error"="failed to perform self check GET request 'http://httpbin.192.168.32.100.xip.io/.well-known/acme-challenge/-_A9EV-TPFS2fmnS51W5qJtStj-qEoo0dyV8bpZjAsk': Get \"http://httpbin.192.168.32.100.xip.io/.well-known/acme-challenge/-_A9EV-TPFS2fmnS51W5qJtStj-qEoo0dyV8bpZjAsk\": EOF" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:33:42.070347       1 pod.go:59] cert-manager/challenges/http01/selfCheck/http01/ensurePod "msg"="found one existing HTTP01 solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-phmlg" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:33:42.070523       1 service.go:43] cert-manager/challenges/http01/selfCheck/http01/ensureService "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-jcbkd" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:33:42.070599       1 ingress.go:110] cert-manager/challenges/http01/selfCheck/http01/ensureIngress "msg"="multiple challenge solver ingresses found for challenge. cleaning up all existing ingresses." "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 16:33:42.078930       1 controller.go:102] ingress 'istio-system/cm-acme-http-solver-4h4dh' in work queue no longer exists
E0405 16:33:42.086346       1 sync.go:186] cert-manager/challenges "msg"="propagation check failed" "error"="multiple existing challenge solver ingresses found and cleaned up. retrying challenge sync" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 16:33:42.086448       1 controller.go:102] ingress 'istio-system/cm-acme-http-solver-6v4mf' in work queue no longer exists
I0405 16:33:42.099342       1 pod.go:59] cert-manager/challenges/http01/selfCheck/http01/ensurePod "msg"="found one existing HTTP01 solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-phmlg" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:33:42.099462       1 service.go:43] cert-manager/challenges/http01/selfCheck/http01/ensureService "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-jcbkd" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 16:33:42.106216       1 sync.go:186] cert-manager/challenges "msg"="propagation check failed" "error"="failed to perform self check GET request 'http://httpbin.192.168.32.100.xip.io/.well-known/acme-challenge/-_A9EV-TPFS2fmnS51W5qJtStj-qEoo0dyV8bpZjAsk': Get \"http://httpbin.192.168.32.100.xip.io/.well-known/acme-challenge/-_A9EV-TPFS2fmnS51W5qJtStj-qEoo0dyV8bpZjAsk\": EOF" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:33:42.126803       1 pod.go:59] cert-manager/challenges/http01/selfCheck/http01/ensurePod "msg"="found one existing HTTP01 solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-phmlg" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:33:42.126956       1 service.go:43] cert-manager/challenges/http01/selfCheck/http01/ensureService "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-jcbkd" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:33:42.127039       1 ingress.go:98] cert-manager/challenges/http01/selfCheck/http01/ensureIngress "msg"="found one existing HTTP01 solver ingress" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Ingress" "related_resource_name"="cm-acme-http-solver-b5jst" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 16:33:42.127933       1 sync.go:186] cert-manager/challenges "msg"="propagation check failed" "error"="failed to perform self check GET request 'http://httpbin.192.168.32.100.xip.io/.well-known/acme-challenge/-_A9EV-TPFS2fmnS51W5qJtStj-qEoo0dyV8bpZjAsk': Get \"http://httpbin.192.168.32.100.xip.io/.well-known/acme-challenge/-_A9EV-TPFS2fmnS51W5qJtStj-qEoo0dyV8bpZjAsk\": EOF" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:33:52.059007       1 pod.go:59] cert-manager/challenges/http01/selfCheck/http01/ensurePod "msg"="found one existing HTTP01 solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-phmlg" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:33:52.059111       1 service.go:43] cert-manager/challenges/http01/selfCheck/http01/ensureService "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-jcbkd" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:33:52.059163       1 ingress.go:98] cert-manager/challenges/http01/selfCheck/http01/ensureIngress "msg"="found one existing HTTP01 solver ingress" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Ingress" "related_resource_name"="cm-acme-http-solver-b5jst" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 16:33:52.060315       1 sync.go:186] cert-manager/challenges "msg"="propagation check failed" "error"="failed to perform self check GET request 'http://httpbin.192.168.32.100.xip.io/.well-known/acme-challenge/-_A9EV-TPFS2fmnS51W5qJtStj-qEoo0dyV8bpZjAsk': Get \"http://httpbin.192.168.32.100.xip.io/.well-known/acme-challenge/-_A9EV-TPFS2fmnS51W5qJtStj-qEoo0dyV8bpZjAsk\": EOF" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:34:02.062097       1 pod.go:59] cert-manager/challenges/http01/selfCheck/http01/ensurePod "msg"="found one existing HTTP01 solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-phmlg" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:34:02.062419       1 service.go:43] cert-manager/challenges/http01/selfCheck/http01/ensureService "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-jcbkd" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:34:02.063008       1 ingress.go:98] cert-manager/challenges/http01/selfCheck/http01/ensureIngress "msg"="found one existing HTTP01 solver ingress" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Ingress" "related_resource_name"="cm-acme-http-solver-b5jst" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 16:34:02.065739       1 sync.go:186] cert-manager/challenges "msg"="propagation check failed" "error"="failed to perform self check GET request 'http://httpbin.192.168.32.100.xip.io/.well-known/acme-challenge/-_A9EV-TPFS2fmnS51W5qJtStj-qEoo0dyV8bpZjAsk': Get \"http://httpbin.192.168.32.100.xip.io/.well-known/acme-challenge/-_A9EV-TPFS2fmnS51W5qJtStj-qEoo0dyV8bpZjAsk\": EOF" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:34:12.067041       1 pod.go:59] cert-manager/challenges/http01/selfCheck/http01/ensurePod "msg"="found one existing HTTP01 solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-phmlg" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:34:12.067507       1 service.go:43] cert-manager/challenges/http01/selfCheck/http01/ensureService "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-jcbkd" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:34:12.067966       1 ingress.go:98] cert-manager/challenges/http01/selfCheck/http01/ensureIngress "msg"="found one existing HTTP01 solver ingress" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Ingress" "related_resource_name"="cm-acme-http-solver-b5jst" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 16:34:12.072629       1 sync.go:186] cert-manager/challenges "msg"="propagation check failed" "error"="failed to perform self check GET request 'http://httpbin.192.168.32.100.xip.io/.well-known/acme-challenge/-_A9EV-TPFS2fmnS51W5qJtStj-qEoo0dyV8bpZjAsk': Get \"http://httpbin.192.168.32.100.xip.io/.well-known/acme-challenge/-_A9EV-TPFS2fmnS51W5qJtStj-qEoo0dyV8bpZjAsk\": EOF" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:34:22.075600       1 pod.go:59] cert-manager/challenges/http01/selfCheck/http01/ensurePod "msg"="found one existing HTTP01 solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-phmlg" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:34:22.075910       1 service.go:43] cert-manager/challenges/http01/selfCheck/http01/ensureService "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-jcbkd" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 16:34:22.076476       1 ingress.go:98] cert-manager/challenges/http01/selfCheck/http01/ensureIngress "msg"="found one existing HTTP01 solver ingress" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Ingress" "related_resource_name"="cm-acme-http-solver-b5jst" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 16:34:33.949307       1 sync.go:386] cert-manager/challenges/acceptChallenge "msg"="error waiting for authorization" "error"="acme: authorization error for httpbin.192.168.32.100.xip.io: 400 urn:ietf:params:acme:error:dns: DNS problem: NXDOMAIN looking up A for httpbin.192.168.32.100.xip.io - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for httpbin.192.168.32.100.xip.io - check that a DNS record exists for this domain" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 16:34:34.088836       1 controller.go:102] ingress 'istio-system/cm-acme-http-solver-b5jst' in work queue no longer exists
I0405 16:34:34.251247       1 conditions.go:190] Found status change for Certificate "httpbin-cert" condition "Issuing": "True" -> "False"; setting lastTransitionTime to 2022-04-05 16:34:34.2512394 +0000 UTC m=+71.187807437
I0405 16:34:34.262628       1 trigger_controller.go:160] cert-manager/certificates-trigger "msg"="Not re-issuing certificate as an attempt has been made in the last hour" "key"="istio-system/httpbin-cert" "retry_delay"=3599737423714
I0405 16:34:34.277873       1 trigger_controller.go:160] cert-manager/certificates-trigger "msg"="Not re-issuing certificate as an attempt has been made in the last hour" "key"="istio-system/httpbin-cert" "retry_delay"=3599722162637
I0405 17:34:34.001193       1 trigger_controller.go:181] cert-manager/certificates-trigger "msg"="Certificate must be re-issued" "key"="istio-system/httpbin-cert" "message"="Issuing certificate as Secret does not exist" "reason"="DoesNotExist"
I0405 17:34:34.001316       1 conditions.go:190] Found status change for Certificate "httpbin-cert" condition "Issuing": "False" -> "True"; setting lastTransitionTime to 2022-04-05 17:34:34.001307143 +0000 UTC m=+3670.937875202
I0405 17:34:34.352125       1 issuing_controller.go:265] cert-manager/certificates-issuing "msg"="Found a failed CertificateRequest from previous issuance, waiting for it to be deleted..." "key"="istio-system/httpbin-cert" "resource_kind"="CertificateRequest" "resource_name"="httpbin-cert-g9tcp" "resource_namespace"="istio-system" "resource_version"="v1" 
I0405 17:34:34.382195       1 conditions.go:261] Setting lastTransitionTime for CertificateRequest "httpbin-cert-shfrw" condition "Approved" to 2022-04-05 17:34:34.382186696 +0000 UTC m=+3671.318754756
I0405 17:34:34.388126       1 util.go:84] cert-manager/controller/certificaterequests/handleOwnedResource "msg"="owning resource not found in cache" "related_resource_kind"="CertificateRequest" "related_resource_name"="httpbin-cert-g9tcp" "related_resource_namespace"="istio-system" "resource_kind"="Order" "resource_name"="httpbin-cert-g9tcp-305099323" "resource_namespace"="istio-system" "resource_version"="v1" 
E0405 17:34:34.388167       1 controller.go:171] cert-manager/orders "msg"="order in work queue no longer exists" "error"="order.acme.cert-manager.io \"httpbin-cert-g9tcp-305099323\" not found"  
I0405 17:34:34.418244       1 util.go:84] cert-manager/controller/orders/handleOwnedResource "msg"="owning resource not found in cache" "related_resource_kind"="Order" "related_resource_name"="httpbin-cert-g9tcp-305099323" "related_resource_namespace"="istio-system" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" 
I0405 17:34:34.425528       1 conditions.go:261] Setting lastTransitionTime for CertificateRequest "httpbin-cert-shfrw" condition "Ready" to 2022-04-05 17:34:34.425517912 +0000 UTC m=+3671.362085972
I0405 17:34:34.453477       1 util.go:84] cert-manager/controller/orders/handleOwnedResource "msg"="owning resource not found in cache" "related_resource_kind"="Order" "related_resource_name"="httpbin-cert-g9tcp-305099323" "related_resource_namespace"="istio-system" "resource_kind"="Challenge" "resource_name"="httpbin-cert-g9tcp-305099323-1818700763" "resource_namespace"="istio-system" "resource_version"="v1" 
E0405 17:34:34.454431       1 controller.go:211] cert-manager/challenges "msg"="challenge in work queue no longer exists" "error"="challenge.acme.cert-manager.io \"httpbin-cert-g9tcp-305099323-1818700763\" not found"  
I0405 17:34:39.228245       1 pod.go:71] cert-manager/challenges/http01/ensurePod "msg"="creating HTTP01 challenge solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 17:34:39.293603       1 pod.go:59] cert-manager/challenges/http01/selfCheck/http01/ensurePod "msg"="found one existing HTTP01 solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-9dt2f" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 17:34:39.293719       1 service.go:43] cert-manager/challenges/http01/selfCheck/http01/ensureService "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-kxh9m" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 17:34:39.293800       1 ingress.go:98] cert-manager/challenges/http01/selfCheck/http01/ensureIngress "msg"="found one existing HTTP01 solver ingress" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Ingress" "related_resource_name"="cm-acme-http-solver-tfxtd" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 17:34:39.394520       1 sync.go:186] cert-manager/challenges "msg"="propagation check failed" "error"="wrong status code '404', expected '200'" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 17:34:39.408552       1 pod.go:59] cert-manager/challenges/http01/selfCheck/http01/ensurePod "msg"="found one existing HTTP01 solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-9dt2f" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 17:34:39.408674       1 service.go:43] cert-manager/challenges/http01/selfCheck/http01/ensureService "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-kxh9m" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 17:34:39.408743       1 ingress.go:98] cert-manager/challenges/http01/selfCheck/http01/ensureIngress "msg"="found one existing HTTP01 solver ingress" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Ingress" "related_resource_name"="cm-acme-http-solver-tfxtd" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 17:34:39.435197       1 sync.go:186] cert-manager/challenges "msg"="propagation check failed" "error"="wrong status code '404', expected '200'" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 17:34:49.395452       1 pod.go:59] cert-manager/challenges/http01/selfCheck/http01/ensurePod "msg"="found one existing HTTP01 solver pod" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-9dt2f" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 17:34:49.395693       1 service.go:43] cert-manager/challenges/http01/selfCheck/http01/ensureService "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-kxh9m" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
I0405 17:34:49.395929       1 ingress.go:98] cert-manager/challenges/http01/selfCheck/http01/ensureIngress "msg"="found one existing HTTP01 solver ingress" "dnsName"="httpbin.192.168.32.100.xip.io" "related_resource_kind"="Ingress" "related_resource_name"="cm-acme-http-solver-tfxtd" "related_resource_namespace"="istio-system" "related_resource_version"="v1" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 17:34:59.966853       1 sync.go:386] cert-manager/challenges/acceptChallenge "msg"="error waiting for authorization" "error"="acme: authorization error for httpbin.192.168.32.100.xip.io: 400 urn:ietf:params:acme:error:dns: DNS problem: NXDOMAIN looking up A for httpbin.192.168.32.100.xip.io - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for httpbin.192.168.32.100.xip.io - check that a DNS record exists for this domain" "dnsName"="httpbin.192.168.32.100.xip.io" "resource_kind"="Challenge" "resource_name"="httpbin-cert-shfrw-305099323-2269462030" "resource_namespace"="istio-system" "resource_version"="v1" "type"="HTTP-01" 
E0405 17:35:00.102277       1 controller.go:102] ingress 'istio-system/cm-acme-http-solver-tfxtd' in work queue no longer exists
I0405 17:35:00.403652       1 conditions.go:190] Found status change for Certificate "httpbin-cert" condition "Issuing": "True" -> "False"; setting lastTransitionTime to 2022-04-05 17:35:00.403646356 +0000 UTC m=+3697.340214387
I0405 17:35:00.415494       1 trigger_controller.go:160] cert-manager/certificates-trigger "msg"="Not re-issuing certificate as an attempt has been made in the last hour" "key"="istio-system/httpbin-cert" "retry_delay"=3599584564360
I0405 17:35:00.433081       1 trigger_controller.go:160] cert-manager/certificates-trigger "msg"="Not re-issuing certificate as an attempt has been made in the last hour" "key"="istio-system/httpbin-cert" "retry_delay"=3599566945063
I0405 17:35:00.437745       1 controller.go:161] cert-manager/certificates-key-manager "msg"="re-queuing item due to optimistic locking on resource" "key"="istio-system/httpbin-cert" "error"="Operation cannot be fulfilled on certificates.cert-manager.io \"httpbin-cert\": the object has been modified; please apply your changes to the latest version and try again"
[root@centos7 aaron]# 

